// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system/ack.proto

package system

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Ack models an acknowledgement of a message.
type Ack struct {
	Count                uint64               `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Submitted            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=submitted,proto3" json:"submitted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec5d8ea51106088, []int{0}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Ack) GetSubmitted() *timestamp.Timestamp {
	if m != nil {
		return m.Submitted
	}
	return nil
}

// Nack models an negative acknowledgement of a message due to an error.
type Nack struct {
	Count                uint64               `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Submitted            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=submitted,proto3" json:"submitted,omitempty"`
	Reason               string               `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Nack) Reset()         { *m = Nack{} }
func (m *Nack) String() string { return proto.CompactTextString(m) }
func (*Nack) ProtoMessage()    {}
func (*Nack) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec5d8ea51106088, []int{1}
}

func (m *Nack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nack.Unmarshal(m, b)
}
func (m *Nack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nack.Marshal(b, m, deterministic)
}
func (m *Nack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nack.Merge(m, src)
}
func (m *Nack) XXX_Size() int {
	return xxx_messageInfo_Nack.Size(m)
}
func (m *Nack) XXX_DiscardUnknown() {
	xxx_messageInfo_Nack.DiscardUnknown(m)
}

var xxx_messageInfo_Nack proto.InternalMessageInfo

func (m *Nack) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Nack) GetSubmitted() *timestamp.Timestamp {
	if m != nil {
		return m.Submitted
	}
	return nil
}

func (m *Nack) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*Ack)(nil), "system.Ack")
	proto.RegisterType((*Nack)(nil), "system.Nack")
}

func init() { proto.RegisterFile("system/ack.proto", fileDescriptor_fec5d8ea51106088) }

var fileDescriptor_fec5d8ea51106088 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0xd0, 0xb1, 0x4a, 0xc5, 0x30,
	0x14, 0x06, 0x60, 0xe2, 0xbd, 0x16, 0x6e, 0x5c, 0x24, 0x88, 0x94, 0x2e, 0x96, 0x4e, 0x45, 0x24,
	0x07, 0x74, 0x71, 0xd5, 0x07, 0x70, 0x28, 0xba, 0xb8, 0x25, 0x31, 0x8d, 0xa1, 0x26, 0xa7, 0x24,
	0x27, 0x83, 0x6f, 0x2f, 0x34, 0x16, 0x5f, 0xc0, 0xf1, 0xff, 0xf9, 0xf9, 0x0e, 0x1c, 0x7e, 0x99,
	0xbf, 0x33, 0xd9, 0x00, 0xca, 0x2c, 0x72, 0x4d, 0x48, 0x28, 0x9a, 0xda, 0x74, 0x37, 0x0e, 0xd1,
	0x7d, 0x59, 0xd8, 0x5a, 0x5d, 0x66, 0x20, 0x1f, 0x6c, 0x26, 0x15, 0xd6, 0x3a, 0x1c, 0xde, 0xf8,
	0xe1, 0xc9, 0x2c, 0xe2, 0x8a, 0x9f, 0x1b, 0x2c, 0x91, 0x5a, 0xd6, 0xb3, 0xf1, 0x38, 0xd5, 0x20,
	0x1e, 0xf9, 0x29, 0x17, 0x1d, 0x3c, 0x91, 0xfd, 0x68, 0xcf, 0x7a, 0x36, 0x5e, 0xdc, 0x77, 0xb2,
	0x8a, 0x72, 0x17, 0xe5, 0xeb, 0x2e, 0x4e, 0x7f, 0xe3, 0x21, 0xf2, 0xe3, 0x8b, 0xfa, 0x7f, 0x57,
	0x5c, 0xf3, 0x26, 0x59, 0x95, 0x31, 0xb6, 0x87, 0x9e, 0x8d, 0xa7, 0xe9, 0x37, 0x3d, 0xdf, 0xbd,
	0xdf, 0x3a, 0x4f, 0x9f, 0x45, 0x4b, 0x83, 0x01, 0x94, 0x4f, 0x41, 0xad, 0xe0, 0x23, 0xd9, 0x34,
	0x2b, 0x63, 0x33, 0xe4, 0x64, 0xc0, 0x21, 0xd4, 0xaf, 0xe8, 0x66, 0x3b, 0xf2, 0xf0, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xd4, 0xaa, 0xff, 0xe0, 0x38, 0x01, 0x00, 0x00,
}
