# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracking/collector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
import extensions_pb2 as extensions__pb2
from system import status_pb2 as system_dot_status__pb2
from system import ack_pb2 as system_dot_ack__pb2
from tracking import identity_pb2 as tracking_dot_identity__pb2
from tracking import track_pb2 as tracking_dot_track__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tracking/collector.proto',
  package='tracking',
  syntax='proto3',
  serialized_options=_b('Z,github.com/airmap/interfaces/src/go/tracking'),
  serialized_pb=_b('\n\x18tracking/collector.proto\x12\x08tracking\x1a\x1egoogle/protobuf/duration.proto\x1a\x10\x65xtensions.proto\x1a\x13system/status.proto\x1a\x10system/ack.proto\x1a\x17tracking/identity.proto\x1a\x14tracking/track.proto\"\x92\x01\n\x19\x43onnectProviderParameters\x12)\n\x02id\x18\x01 \x01(\x0b\x32\x1d.tracking.Identity.ProviderId\x12J\n!expected_duration_between_updates\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationB\x04\x80\xa6\x1d\x01\"7\n\x1a\x43onnectProcessorParameters\x12\x19\n\x11\x65nable_projection\x18\x01 \x01(\x08\"\xf3\x03\n\x06Update\x1a\x9a\x01\n\x0c\x46romProvider\x12 \n\x06status\x18\x01 \x01(\x0b\x32\x0e.system.StatusH\x00\x12&\n\x05\x62\x61tch\x18\x02 \x01(\x0b\x32\x15.tracking.Track.BatchH\x00\x12\x35\n\x06params\x18\x03 \x01(\x0b\x32#.tracking.ConnectProviderParametersH\x00\x42\t\n\x07\x64\x65tails\x1aU\n\nToProvider\x12 \n\x06status\x18\x01 \x01(\x0b\x32\x0e.system.StatusH\x00\x12\x1a\n\x03\x61\x63k\x18\x02 \x01(\x0b\x32\x0b.system.AckH\x00\x42\t\n\x07\x64\x65tails\x1a\x62\n\x0bToProcessor\x12 \n\x06status\x18\x01 \x01(\x0b\x32\x0e.system.StatusH\x00\x12&\n\x05\x62\x61tch\x18\x02 \x01(\x0b\x32\x15.tracking.Track.BatchH\x00\x42\t\n\x07\x64\x65tails\x1a\x90\x01\n\rFromProcessor\x12 \n\x06status\x18\x01 \x01(\x0b\x32\x0e.system.StatusH\x00\x12\x1a\n\x03\x61\x63k\x18\x02 \x01(\x0b\x32\x0b.system.AckH\x00\x12\x36\n\x06params\x18\x03 \x01(\x0b\x32$.tracking.ConnectProcessorParametersH\x00\x42\t\n\x07\x64\x65tails2\xb4\x01\n\tCollector\x12Q\n\x0f\x43onnectProvider\x12\x1d.tracking.Update.FromProvider\x1a\x1b.tracking.Update.ToProvider(\x01\x30\x01\x12T\n\x10\x43onnectProcessor\x12\x1e.tracking.Update.FromProcessor\x1a\x1c.tracking.Update.ToProcessor(\x01\x30\x01\x42.Z,github.com/airmap/interfaces/src/go/trackingb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,extensions__pb2.DESCRIPTOR,system_dot_status__pb2.DESCRIPTOR,system_dot_ack__pb2.DESCRIPTOR,tracking_dot_identity__pb2.DESCRIPTOR,tracking_dot_track__pb2.DESCRIPTOR,])




_CONNECTPROVIDERPARAMETERS = _descriptor.Descriptor(
  name='ConnectProviderParameters',
  full_name='tracking.ConnectProviderParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tracking.ConnectProviderParameters.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expected_duration_between_updates', full_name='tracking.ConnectProviderParameters.expected_duration_between_updates', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\200\246\035\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=321,
)


_CONNECTPROCESSORPARAMETERS = _descriptor.Descriptor(
  name='ConnectProcessorParameters',
  full_name='tracking.ConnectProcessorParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable_projection', full_name='tracking.ConnectProcessorParameters.enable_projection', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=378,
)


_UPDATE_FROMPROVIDER = _descriptor.Descriptor(
  name='FromProvider',
  full_name='tracking.Update.FromProvider',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='tracking.Update.FromProvider.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch', full_name='tracking.Update.FromProvider.batch', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='tracking.Update.FromProvider.params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='details', full_name='tracking.Update.FromProvider.details',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=392,
  serialized_end=546,
)

_UPDATE_TOPROVIDER = _descriptor.Descriptor(
  name='ToProvider',
  full_name='tracking.Update.ToProvider',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='tracking.Update.ToProvider.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ack', full_name='tracking.Update.ToProvider.ack', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='details', full_name='tracking.Update.ToProvider.details',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=548,
  serialized_end=633,
)

_UPDATE_TOPROCESSOR = _descriptor.Descriptor(
  name='ToProcessor',
  full_name='tracking.Update.ToProcessor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='tracking.Update.ToProcessor.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch', full_name='tracking.Update.ToProcessor.batch', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='details', full_name='tracking.Update.ToProcessor.details',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=635,
  serialized_end=733,
)

_UPDATE_FROMPROCESSOR = _descriptor.Descriptor(
  name='FromProcessor',
  full_name='tracking.Update.FromProcessor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='tracking.Update.FromProcessor.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ack', full_name='tracking.Update.FromProcessor.ack', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='tracking.Update.FromProcessor.params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='details', full_name='tracking.Update.FromProcessor.details',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=736,
  serialized_end=880,
)

_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='tracking.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_UPDATE_FROMPROVIDER, _UPDATE_TOPROVIDER, _UPDATE_TOPROCESSOR, _UPDATE_FROMPROCESSOR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=880,
)

_CONNECTPROVIDERPARAMETERS.fields_by_name['id'].message_type = tracking_dot_identity__pb2._IDENTITY_PROVIDERID
_CONNECTPROVIDERPARAMETERS.fields_by_name['expected_duration_between_updates'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_UPDATE_FROMPROVIDER.fields_by_name['status'].message_type = system_dot_status__pb2._STATUS
_UPDATE_FROMPROVIDER.fields_by_name['batch'].message_type = tracking_dot_track__pb2._TRACK_BATCH
_UPDATE_FROMPROVIDER.fields_by_name['params'].message_type = _CONNECTPROVIDERPARAMETERS
_UPDATE_FROMPROVIDER.containing_type = _UPDATE
_UPDATE_FROMPROVIDER.oneofs_by_name['details'].fields.append(
  _UPDATE_FROMPROVIDER.fields_by_name['status'])
_UPDATE_FROMPROVIDER.fields_by_name['status'].containing_oneof = _UPDATE_FROMPROVIDER.oneofs_by_name['details']
_UPDATE_FROMPROVIDER.oneofs_by_name['details'].fields.append(
  _UPDATE_FROMPROVIDER.fields_by_name['batch'])
_UPDATE_FROMPROVIDER.fields_by_name['batch'].containing_oneof = _UPDATE_FROMPROVIDER.oneofs_by_name['details']
_UPDATE_FROMPROVIDER.oneofs_by_name['details'].fields.append(
  _UPDATE_FROMPROVIDER.fields_by_name['params'])
_UPDATE_FROMPROVIDER.fields_by_name['params'].containing_oneof = _UPDATE_FROMPROVIDER.oneofs_by_name['details']
_UPDATE_TOPROVIDER.fields_by_name['status'].message_type = system_dot_status__pb2._STATUS
_UPDATE_TOPROVIDER.fields_by_name['ack'].message_type = system_dot_ack__pb2._ACK
_UPDATE_TOPROVIDER.containing_type = _UPDATE
_UPDATE_TOPROVIDER.oneofs_by_name['details'].fields.append(
  _UPDATE_TOPROVIDER.fields_by_name['status'])
_UPDATE_TOPROVIDER.fields_by_name['status'].containing_oneof = _UPDATE_TOPROVIDER.oneofs_by_name['details']
_UPDATE_TOPROVIDER.oneofs_by_name['details'].fields.append(
  _UPDATE_TOPROVIDER.fields_by_name['ack'])
_UPDATE_TOPROVIDER.fields_by_name['ack'].containing_oneof = _UPDATE_TOPROVIDER.oneofs_by_name['details']
_UPDATE_TOPROCESSOR.fields_by_name['status'].message_type = system_dot_status__pb2._STATUS
_UPDATE_TOPROCESSOR.fields_by_name['batch'].message_type = tracking_dot_track__pb2._TRACK_BATCH
_UPDATE_TOPROCESSOR.containing_type = _UPDATE
_UPDATE_TOPROCESSOR.oneofs_by_name['details'].fields.append(
  _UPDATE_TOPROCESSOR.fields_by_name['status'])
_UPDATE_TOPROCESSOR.fields_by_name['status'].containing_oneof = _UPDATE_TOPROCESSOR.oneofs_by_name['details']
_UPDATE_TOPROCESSOR.oneofs_by_name['details'].fields.append(
  _UPDATE_TOPROCESSOR.fields_by_name['batch'])
_UPDATE_TOPROCESSOR.fields_by_name['batch'].containing_oneof = _UPDATE_TOPROCESSOR.oneofs_by_name['details']
_UPDATE_FROMPROCESSOR.fields_by_name['status'].message_type = system_dot_status__pb2._STATUS
_UPDATE_FROMPROCESSOR.fields_by_name['ack'].message_type = system_dot_ack__pb2._ACK
_UPDATE_FROMPROCESSOR.fields_by_name['params'].message_type = _CONNECTPROCESSORPARAMETERS
_UPDATE_FROMPROCESSOR.containing_type = _UPDATE
_UPDATE_FROMPROCESSOR.oneofs_by_name['details'].fields.append(
  _UPDATE_FROMPROCESSOR.fields_by_name['status'])
_UPDATE_FROMPROCESSOR.fields_by_name['status'].containing_oneof = _UPDATE_FROMPROCESSOR.oneofs_by_name['details']
_UPDATE_FROMPROCESSOR.oneofs_by_name['details'].fields.append(
  _UPDATE_FROMPROCESSOR.fields_by_name['ack'])
_UPDATE_FROMPROCESSOR.fields_by_name['ack'].containing_oneof = _UPDATE_FROMPROCESSOR.oneofs_by_name['details']
_UPDATE_FROMPROCESSOR.oneofs_by_name['details'].fields.append(
  _UPDATE_FROMPROCESSOR.fields_by_name['params'])
_UPDATE_FROMPROCESSOR.fields_by_name['params'].containing_oneof = _UPDATE_FROMPROCESSOR.oneofs_by_name['details']
DESCRIPTOR.message_types_by_name['ConnectProviderParameters'] = _CONNECTPROVIDERPARAMETERS
DESCRIPTOR.message_types_by_name['ConnectProcessorParameters'] = _CONNECTPROCESSORPARAMETERS
DESCRIPTOR.message_types_by_name['Update'] = _UPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectProviderParameters = _reflection.GeneratedProtocolMessageType('ConnectProviderParameters', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTPROVIDERPARAMETERS,
  '__module__' : 'tracking.collector_pb2'
  # @@protoc_insertion_point(class_scope:tracking.ConnectProviderParameters)
  })
_sym_db.RegisterMessage(ConnectProviderParameters)

ConnectProcessorParameters = _reflection.GeneratedProtocolMessageType('ConnectProcessorParameters', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTPROCESSORPARAMETERS,
  '__module__' : 'tracking.collector_pb2'
  # @@protoc_insertion_point(class_scope:tracking.ConnectProcessorParameters)
  })
_sym_db.RegisterMessage(ConnectProcessorParameters)

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), {

  'FromProvider' : _reflection.GeneratedProtocolMessageType('FromProvider', (_message.Message,), {
    'DESCRIPTOR' : _UPDATE_FROMPROVIDER,
    '__module__' : 'tracking.collector_pb2'
    # @@protoc_insertion_point(class_scope:tracking.Update.FromProvider)
    })
  ,

  'ToProvider' : _reflection.GeneratedProtocolMessageType('ToProvider', (_message.Message,), {
    'DESCRIPTOR' : _UPDATE_TOPROVIDER,
    '__module__' : 'tracking.collector_pb2'
    # @@protoc_insertion_point(class_scope:tracking.Update.ToProvider)
    })
  ,

  'ToProcessor' : _reflection.GeneratedProtocolMessageType('ToProcessor', (_message.Message,), {
    'DESCRIPTOR' : _UPDATE_TOPROCESSOR,
    '__module__' : 'tracking.collector_pb2'
    # @@protoc_insertion_point(class_scope:tracking.Update.ToProcessor)
    })
  ,

  'FromProcessor' : _reflection.GeneratedProtocolMessageType('FromProcessor', (_message.Message,), {
    'DESCRIPTOR' : _UPDATE_FROMPROCESSOR,
    '__module__' : 'tracking.collector_pb2'
    # @@protoc_insertion_point(class_scope:tracking.Update.FromProcessor)
    })
  ,
  'DESCRIPTOR' : _UPDATE,
  '__module__' : 'tracking.collector_pb2'
  # @@protoc_insertion_point(class_scope:tracking.Update)
  })
_sym_db.RegisterMessage(Update)
_sym_db.RegisterMessage(Update.FromProvider)
_sym_db.RegisterMessage(Update.ToProvider)
_sym_db.RegisterMessage(Update.ToProcessor)
_sym_db.RegisterMessage(Update.FromProcessor)


DESCRIPTOR._options = None
_CONNECTPROVIDERPARAMETERS.fields_by_name['expected_duration_between_updates']._options = None

_COLLECTOR = _descriptor.ServiceDescriptor(
  name='Collector',
  full_name='tracking.Collector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=883,
  serialized_end=1063,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConnectProvider',
    full_name='tracking.Collector.ConnectProvider',
    index=0,
    containing_service=None,
    input_type=_UPDATE_FROMPROVIDER,
    output_type=_UPDATE_TOPROVIDER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConnectProcessor',
    full_name='tracking.Collector.ConnectProcessor',
    index=1,
    containing_service=None,
    input_type=_UPDATE_FROMPROCESSOR,
    output_type=_UPDATE_TOPROCESSOR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COLLECTOR)

DESCRIPTOR.services_by_name['Collector'] = _COLLECTOR

# @@protoc_insertion_point(module_scope)
