# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracking/emitter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import extensions_pb2 as extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tracking/emitter.proto',
  package='tracking',
  syntax='proto3',
  serialized_options=_b('Z,github.com/airmap/interfaces/src/go/tracking'),
  serialized_pb=_b('\n\x16tracking/emitter.proto\x12\x08tracking\x1a\x10\x65xtensions.proto*\x89\x04\n\x07\x45mitter\x12\x13\n\x0f\x45MITTER_UNKNOWN\x10\x00\x12\x1a\n\x16\x45MITTER_LIGHT_AIRCRAFT\x10\x01\x12\x1a\n\x16\x45MITTER_SMALL_AIRCRAFT\x10\x02\x12\x1b\n\x17\x45MITTER_MEDIUM_AIRCRAFT\x10\x03\x12\x1a\n\x16\x45MITTER_LARGE_AIRCRAFT\x10\x04\x12\x19\n\x15\x45MITTER_HEAVY_AIRCAFT\x10\x05\x12\x1f\n\x1b\x45MITTER_HIGHLY_MANUEVERABLE\x10\x06\x12\x16\n\x12\x45MITTER_ROTORCRAFT\x10\n\x12\x12\n\x0e\x45MITTER_GLIDER\x10\x0b\x12\x1c\n\x18\x45MITTER_LIGHTER_THAN_AIR\x10\x0c\x12\x0f\n\x0b\x45MITTER_UAV\x10\r\x12\x11\n\rEMITTER_SPACE\x10\x0e\x12\x16\n\x12\x45MITTER_ULTRALIGHT\x10\x0f\x12\x17\n\x13\x45MITTER_PARACHUTIST\x10\x10\x12!\n\x1d\x45MITTER_SFC_EMERGENCY_VEHICLE\x10\x14\x12\x1f\n\x1b\x45MITTER_SFC_SERVICE_VEHICLE\x10\x15\x12\x18\n\x14\x45MITTER_SFC_OBSTACLE\x10\x16\x12 \n\x1c\x45MITTER_SFC_OBSTACLE_CLUSTER\x10\x17\x12\x1d\n\x19\x45MITTER_SFC_OBSTACLE_LINE\x10\x18\x42.Z,github.com/airmap/interfaces/src/go/trackingb\x06proto3')
  ,
  dependencies=[extensions__pb2.DESCRIPTOR,])

_EMITTER = _descriptor.EnumDescriptor(
  name='Emitter',
  full_name='tracking.Emitter',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMITTER_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_LIGHT_AIRCRAFT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_SMALL_AIRCRAFT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_MEDIUM_AIRCRAFT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_LARGE_AIRCRAFT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_HEAVY_AIRCAFT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_HIGHLY_MANUEVERABLE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_ROTORCRAFT', index=7, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_GLIDER', index=8, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_LIGHTER_THAN_AIR', index=9, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_UAV', index=10, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_SPACE', index=11, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_ULTRALIGHT', index=12, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_PARACHUTIST', index=13, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_SFC_EMERGENCY_VEHICLE', index=14, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_SFC_SERVICE_VEHICLE', index=15, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_SFC_OBSTACLE', index=16, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_SFC_OBSTACLE_CLUSTER', index=17, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMITTER_SFC_OBSTACLE_LINE', index=18, number=24,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=55,
  serialized_end=576,
)
_sym_db.RegisterEnumDescriptor(_EMITTER)

Emitter = enum_type_wrapper.EnumTypeWrapper(_EMITTER)
EMITTER_UNKNOWN = 0
EMITTER_LIGHT_AIRCRAFT = 1
EMITTER_SMALL_AIRCRAFT = 2
EMITTER_MEDIUM_AIRCRAFT = 3
EMITTER_LARGE_AIRCRAFT = 4
EMITTER_HEAVY_AIRCAFT = 5
EMITTER_HIGHLY_MANUEVERABLE = 6
EMITTER_ROTORCRAFT = 10
EMITTER_GLIDER = 11
EMITTER_LIGHTER_THAN_AIR = 12
EMITTER_UAV = 13
EMITTER_SPACE = 14
EMITTER_ULTRALIGHT = 15
EMITTER_PARACHUTIST = 16
EMITTER_SFC_EMERGENCY_VEHICLE = 20
EMITTER_SFC_SERVICE_VEHICLE = 21
EMITTER_SFC_OBSTACLE = 22
EMITTER_SFC_OBSTACLE_CLUSTER = 23
EMITTER_SFC_OBSTACLE_LINE = 24


DESCRIPTOR.enum_types_by_name['Emitter'] = _EMITTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
