# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry/archive.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
import extensions_pb2 as extensions__pb2
from ids import ids_pb2 as ids_dot_ids__pb2
from telemetry import report_pb2 as telemetry_dot_report__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='telemetry/archive.proto',
  package='telemetry',
  syntax='proto3',
  serialized_options=_b('Z-github.com/airmap/interfaces/src/go/telemetry'),
  serialized_pb=_b('\n\x17telemetry/archive.proto\x12\ttelemetry\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x10\x65xtensions.proto\x1a\rids/ids.proto\x1a\x16telemetry/report.proto\"\xcf\x01\n\x0eOperationQuery\x12!\n\toperation\x18\x01 \x01(\x0b\x32\x0e.ids.Operation\x12/\n\x05start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\x80\xa6\x1d\x01\x12-\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\x80\xa6\x1d\x01\x12:\n\x0bsample_rate\x18\x04 \x01(\x0b\x32\x19.google.protobuf.DurationB\n\x80\xa6\x1d\x01\x8a\xa7\x1d\x02\x08\x01\x32R\n\x07\x41rchive\x12G\n\x15QueryOperationReports\x12\x19.telemetry.OperationQuery\x1a\x11.telemetry.Report0\x01\x42/Z-github.com/airmap/interfaces/src/go/telemetryb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,extensions__pb2.DESCRIPTOR,ids_dot_ids__pb2.DESCRIPTOR,telemetry_dot_report__pb2.DESCRIPTOR,])




_OPERATIONQUERY = _descriptor.Descriptor(
  name='OperationQuery',
  full_name='telemetry.OperationQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='telemetry.OperationQuery.operation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='telemetry.OperationQuery.start', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\200\246\035\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='telemetry.OperationQuery.end', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\200\246\035\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='telemetry.OperationQuery.sample_rate', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\200\246\035\001\212\247\035\002\010\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=368,
)

_OPERATIONQUERY.fields_by_name['operation'].message_type = ids_dot_ids__pb2._OPERATION
_OPERATIONQUERY.fields_by_name['start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OPERATIONQUERY.fields_by_name['end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_OPERATIONQUERY.fields_by_name['sample_rate'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['OperationQuery'] = _OPERATIONQUERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OperationQuery = _reflection.GeneratedProtocolMessageType('OperationQuery', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONQUERY,
  '__module__' : 'telemetry.archive_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.OperationQuery)
  })
_sym_db.RegisterMessage(OperationQuery)


DESCRIPTOR._options = None
_OPERATIONQUERY.fields_by_name['start']._options = None
_OPERATIONQUERY.fields_by_name['end']._options = None
_OPERATIONQUERY.fields_by_name['sample_rate']._options = None

_ARCHIVE = _descriptor.ServiceDescriptor(
  name='Archive',
  full_name='telemetry.Archive',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=370,
  serialized_end=452,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryOperationReports',
    full_name='telemetry.Archive.QueryOperationReports',
    index=0,
    containing_service=None,
    input_type=_OPERATIONQUERY,
    output_type=telemetry_dot_report__pb2._REPORT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARCHIVE)

DESCRIPTOR.services_by_name['Archive'] = _ARCHIVE

# @@protoc_insertion_point(module_scope)
